# Generated by Django 3.0 on 2021-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default='new'),
        ),
    ]
